# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=200, unique=True)),
                ('image_url', models.CharField(max_length=1000)),
                ('cover_url', models.CharField(max_length=1000)),
                ('event_date', models.DateField(db_index=True)),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=200, unique=True)),
                ('image_url', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
