# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=200, unique=True)),
                ('image_url', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
