# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Event',
        ),
    ]
