# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='NYC', max_length=200),
            preserve_default=False,
        ),
    ]
