# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160608_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
